permissions: read-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  formatBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - uses: docker://ghcr.io/fluidattacks/makes:24.09
        name: /formatBash
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatBash"

  formatNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - uses: docker://ghcr.io/fluidattacks/makes:24.09
        name: /formatNix
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatNix"

  lintBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - uses: docker://ghcr.io/fluidattacks/makes:24.09
        name: /lintBash
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintBash"

  lintMarkdown_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - uses: docker://ghcr.io/fluidattacks/makes:24.09
        name: /lintMarkdown/all
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintMarkdown/all"

  eslintAndPrettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - uses: actions/setup-node@aca7b64a59c0063db8564e0ffdadd3887f1cbae5
        with:
          node-version: 22
      - run: npm ci
      - run: npm run eslint
      - run: npm run format:check
      - run: npm run check
      - run: npm run cy:eslint

  lintGitCommitMsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
        with:
          fetch-depth: 0
      - uses: docker://ghcr.io/fluidattacks/makes:24.09
        name: /lintGitCommitMsg
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintGitCommitMsg"

name: dev
on:
  pull_request:
    branches: [main]
  push:
    branches: [development]
