permissions: read-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}
jobs:
  linux_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: __all__
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . __all__"

  formatBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /formatBash
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatBash"

  formatNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /formatNix
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatNix"

  formatYaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /formatYaml
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /formatYaml"

  lintBash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintBash
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintBash"

  lintGitCommitMsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintGitCommitMsg
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintGitCommitMsg"

  lintMarkdown_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintMarkdown/all
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintMarkdown/all"

  lintNix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/nixos/nix@sha256:c3db4c484f6b1ee6c9bb8ca90307cfbeca8ef88156840911356a677eeaff4845
        name: /lintNix
        with:
          args: sh -c "chown -R root:root /github/workspace && nix-env -if . && m . /lintNix"
name: dev
on:
  push:
    branches: [main]
